version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/server/scraper"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
