//
//  FacebookLogin.m
//  Hydra
//
//  Created by Feliciaan De Palmenaer on 7/01/13.
//  Copyright (c) 2013 Zeus WPI. All rights reserved.
//

#import "FacebookSession.h"
#import "AppDelegate.h"
#import <FacebookSDK/FacebookSDK.h>

// Generated by visiting https://graph.facebook.com/oauth/access_token?client_id=_&client_secret=_&grant_type=client_credentials
#define kAppAccessToken @"146947948791011|QqOR99OREkC_vAvOkfJm2tp-02k"

NSString *const FacebookSessionStateChangedNotification =
    @"FacebookSessionStateChangedNotification";
NSString *const FacebookUserInfoUpdatedNotifcation =
    @"FacebookUserInfoUpdatedNotifcation";

@interface FacebookSession ()

@property (nonatomic, strong) NSString *appAccessToken;
@property (nonatomic, strong) id<FBGraphUser> userInfo;

@end

@implementation FacebookSession

+ (FacebookSession *)sharedSession
{
    static FacebookSession *sharedInstance = nil;
    if (!sharedInstance) {
        sharedInstance = [[FacebookSession alloc] init];
    }
    return sharedInstance;
}

#pragma mark - Session management

- (BOOL)openWithAllowLoginUI:(BOOL)allowLoginUI
{
    return [self openWithAllowLoginUI:allowLoginUI completion:NULL];
}

- (BOOL)openWithAllowLoginUI:(BOOL)allowLoginUI completion:(void (^)())completion
{
    FBSessionStateHandler handler = ^(FBSession *session, FBSessionState state, NSError *error) {
        [self sessionStateChanged:session state:state error:error];
        if (!error && completion) {
            completion();
        }
    };

    return [FBSession openActiveSessionWithPublishPermissions:@[@"rsvp_event"]
                                              defaultAudience:FBSessionDefaultAudienceFriends
                                                 allowLoginUI:allowLoginUI completionHandler:handler];
}

- (void)close
{
    [[FBSession activeSession] closeAndClearTokenInformation];
}

- (BOOL)open
{
    return [[FBSession activeSession] isOpen];
}

- (void)sessionStateChanged:(FBSession *)session state:(FBSessionState)state error:(NSError *)error
{
    DLog(@"%@ %@", session, error);
    switch (state) {
        case FBSessionStateClosed:
        case FBSessionStateClosedLoginFailed:
            self.userInfo = nil;
            [[FBSession activeSession] closeAndClearTokenInformation];
            break;
        default:
            break;
    }

    NSNotificationCenter *center = [NSNotificationCenter defaultCenter];
    [center postNotificationName:FacebookSessionStateChangedNotification object:session];

    if (error) {
        AppDelegate *delegate = (AppDelegate *)[[UIApplication sharedApplication] delegate];
        [delegate handleError:error];
    }
}

#pragma mark - User info

- (id<FBGraphUser>)userInfo
{
    if (self.open && !_userInfo) {
        [self updateUserInfo];
    }
    return _userInfo;
}

- (void)updateUserInfo
{
    FBRequest *request = [FBRequest requestForMe];
    [request startWithCompletionHandler:^(FBRequestConnection *c, id result, NSError *error) {
        if (error) {
            NSLog(@"Error while fetching user information: %@", [error localizedDescription]);
        }
        else {
            self.userInfo = result;

            NSNotificationCenter *center = [NSNotificationCenter defaultCenter];
            [center postNotificationName:FacebookUserInfoUpdatedNotifcation object:result];
        }
    }];
}

#pragma mark - Request helpers

- (FBRequest *)requestWithGraphPath:(NSString *)path parameters:(NSDictionary *)parameters
{
    return [self requestWithGraphPath:path parameters:parameters HTTPMethod:@"GET"];
}

- (FBRequest *)requestWithQuery:(NSString *)query
{
    return [self requestWithGraphPath:@"/fql" parameters:@{@"q": query} HTTPMethod:@"GET"];
}

- (FBRequest *)requestWithGraphPath:(NSString *)path parameters:(NSDictionary *)parameters HTTPMethod:(NSString *)method
{
    FBSession *session = [FBSession activeSession];

    // If there's no session, try accessing the resource with the app token
    if (![session isOpen] && ![FBSession openActiveSessionWithAllowLoginUI:NO]) {
        NSMutableDictionary *mutableParams = [parameters mutableCopy];
        if (!mutableParams) {
            mutableParams = [NSMutableDictionary dictionary];
        }
        mutableParams[@"access_token"] = kAppAccessToken;

        session = nil;
        parameters = mutableParams;
    }

    return [[FBRequest alloc] initWithSession:session graphPath:path
                                   parameters:parameters HTTPMethod:method];
}

@end
