language: generic

# We need nodejs for some json tests
node_js:
  - "8"

# We need the JDK for HTML test
jdk:
  openjdk8

python:
  - "3.6"

addons:
  ssh_known_hosts: zeus.ugent.be:2222

before_install:
# - sudo apt-get update
- sudo apt-get install -y realpath
- sudo apt-get install -y shellcheck
- openssl aes-256-cbc -K $encrypted_9715c79dd19b_key -iv $encrypted_9715c79dd19b_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
#- echo -e "Host zeus.ugent.be\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
# Set global python version
- pyenv install 3.6.8
- pyenv global 3.6.8

# Install the tool for the tests.
# The requirements for the deployment test are installed by the scripts themselves.
before_script:
- npm install -g ajv-cli@3.0.0
- pip install html5validator==0.3.1 --user

script:
- "./server/test.sh"

branches:
  only:
  - master

deploy:
  provider: script
  script: ./server/deploy.sh ./server/
  skip_cleanup: true
  on:
    branch: master
