language: node_js
node_js:
- '8'
addons:
  apt:
    packages:
    - openjdk-8-jre  # install Java8 as required by vnu.jar
install:
- npm install -g ajv-cli
- pip install html5validator --user
script: cd server/tests && ./association.sh && ./info.sh && ./website.sh
cache:
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_5ba2058eb1b7_key -iv $encrypted_5ba2058eb1b7_iv
  -in id_travis_rsa.enc -out ~/.ssh/id_travis_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ~/.ssh/id_travis_rsa
- ssh-add ~/.ssh/id_travis_rsa
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master