language: node_js
node_js:
  - "8"

# Install the tool for the tests
before_script:
  - npm install -g ajv-cli

# Run our tests
script: validation/validator.sh

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master