language: node_js
node_js:
  - "8"

jdk:
  openjdk8

python:
  - "3.7"

# Install the tool for the tests
before_script:
  - npm install -g ajv-cli@3.0.0
  - pip install html5validator==0.3.1

script:
  - cd server && ./tester.sh

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master

deploy:
  - provider: script
    script: cd server  && ./deployer.sh
    on:
      branch: master