dist: bionic
language: generic

# We need following base languages and versions:
# - Python >= 3.6 (tested on 3.7)
# - Node >= 8 (tested on 10.16)
# - Java >= 8 (tested on 11)

addons:
  ssh_known_hosts: zeus.ugent.be:2222
  apt:
    packages:
      - coreutils
      - shellcheck
      - librsvg2-bin
      - imagemagick
      - libmagickcore-6.q16-3-extra

before_install:
  - openssl aes-256-cbc -K $encrypted_9715c79dd19b_key -iv $encrypted_9715c79dd19b_iv -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key

install:
  - pyenv versions | grep '3.7' | xargs -I{} pyenv global {}
  - npm install -g ajv-cli@3.0.0
  - pip install html5validator==0.3.1 --user

script:
  - "./server/test.sh"

branches:
  only:
    - master

deploy:
  provider: script
  script: ./server/deploy.sh ./server/
  skip_cleanup: true
  on:
    branch: master
