version: '3.8'

services:
  app:
    build: .
    ports:
      - 8012:8000
    environment:
      FLASK_ENV: 'production'
      PUBLIC_DIR: '/hydra_public'
      SCRAPER_DIR: '/hydra_scraper'
    volumes:
    - ../public:/hydra_public
    - ../scraper:/hydra_scraper