/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package be.ugent.zeus.resto.client;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int icon_meal=0x7f020001;
        public static final int icon_soup=0x7f020002;
        public static final int icon_vegetables=0x7f020003;
        public static final int line=0x7f020004;
        public static final int red=0x7f020005;
    }
    public static final class id {
        public static final int widget102=0x7f050005;
        public static final int widget103=0x7f050006;
        public static final int widget28=0x7f050001;
        public static final int widget30=0x7f050000;
        public static final int widget31=0x7f050004;
        public static final int widget34=0x7f050003;
        public static final int widget36=0x7f050002;
        public static final int widget76=0x7f050007;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
