/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package be.ugent.zeus.resto.client;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int androidmarker=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int icon_meal=0x7f020002;
        public static final int icon_soup=0x7f020003;
        public static final int icon_vegetables=0x7f020004;
        public static final int line=0x7f020005;
        public static final int red=0x7f020006;
    }
    public static final class id {
        public static final int day=0x7f060000;
        public static final int mapview=0x7f060005;
        public static final int meat=0x7f060003;
        public static final int show_about=0x7f060007;
        public static final int show_map=0x7f060006;
        public static final int soup=0x7f060001;
        public static final int soup_price=0x7f060002;
        public static final int vegetables=0x7f060004;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int restomap=0x7f030001;
        public static final int unavailable=0x7f030002;
    }
    public static final class menu {
        public static final int viewmap=0x7f050000;
    }
    public static final class string {
        public static final int about=0x7f040007;
        public static final int app_name=0x7f040000;
        public static final int meat=0x7f040004;
        public static final int show_map=0x7f040006;
        public static final int soup=0x7f040003;
        public static final int today=0x7f040001;
        public static final int tomorrow=0x7f040002;
        public static final int vegetables=0x7f040005;
    }
}
